-- SISTEMA HOSPITALAR - BANCO DE DADOS RELACIONAL (ORACLE SQL DEVELOPER)

-- =============================
-- 1. CRIAÇÃO DAS TABELAS
-- =============================

CREATE TABLE Especialidade (
    id_especialidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_especialidade VARCHAR2(100) NOT NULL
);

CREATE TABLE Medico (
    id_medico NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    crm VARCHAR2(20) UNIQUE NOT NULL,
    telefone VARCHAR2(20),
    id_especialidade NUMBER NOT NULL,
    CONSTRAINT fk_medico_especialidade
        FOREIGN KEY (id_especialidade) REFERENCES Especialidade(id_especialidade)
);

CREATE TABLE Paciente (
    id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) UNIQUE NOT NULL,
    data_nascimento DATE,
    telefone VARCHAR2(20),
    endereco VARCHAR2(150)
);

CREATE TABLE Setor (
    id_setor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_setor VARCHAR2(100) NOT NULL,
    andar NUMBER
);

CREATE TABLE Consulta (
    id_consulta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente NUMBER NOT NULL,
    id_medico NUMBER NOT NULL,
    data_consulta DATE NOT NULL,
    diagnostico VARCHAR2(200),
    receita VARCHAR2(300),
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente),
    CONSTRAINT fk_consulta_medico FOREIGN KEY (id_medico) REFERENCES Medico(id_medico)
);

CREATE TABLE Internacao (
    id_internacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente NUMBER NOT NULL,
    id_setor NUMBER NOT NULL,
    data_entrada DATE NOT NULL,
    data_saida DATE,
    observacoes VARCHAR2(300),
    CONSTRAINT fk_internacao_paciente FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente),
    CONSTRAINT fk_internacao_setor FOREIGN KEY (id_setor) REFERENCES Setor(id_setor)
);

-- =============================
-- 2. INSERÇÃO DE DADOS EXEMPLO
-- =============================

-- Especialidades
INSERT INTO Especialidade (nome_especialidade) VALUES ('Cardiologia');
INSERT INTO Especialidade (nome_especialidade) VALUES ('Pediatria');
INSERT INTO Especialidade (nome_especialidade) VALUES ('Ortopedia');

-- Médicos
INSERT INTO Medico (nome, crm, telefone, id_especialidade)
VALUES ('Dr. João Mendes', 'CRM12345', '(47) 99999-0001', 1);

INSERT INTO Medico (nome, crm, telefone, id_especialidade)
VALUES ('Dra. Maria Costa', 'CRM67890', '(47) 99999-0002', 2);

-- Pacientes
INSERT INTO Paciente (nome, cpf, data_nascimento, telefone, endereco)
VALUES ('Carlos Silva', '123.456.789-00', TO_DATE('1980-03-15', 'YYYY-MM-DD'), '(47) 98888-1111', 'Rua das Flores, 120');

INSERT INTO Paciente (nome, cpf, data_nascimento, telefone, endereco)
VALUES ('Ana Souza', '987.654.321-00', TO_DATE('1995-07-20', 'YYYY-MM-DD'), '(47) 98888-2222', 'Av. Central, 45');

-- Setores
INSERT INTO Setor (nome_setor, andar) VALUES ('Emergência', 1);
INSERT INTO Setor (nome_setor, andar) VALUES ('UTI', 2);
INSERT INTO Setor (nome_setor, andar) VALUES ('Internação Geral', 3);

-- Consultas
INSERT INTO Consulta (id_paciente, id_medico, data_consulta, diagnostico, receita)
VALUES (1, 1, TO_DATE('2025-11-10', 'YYYY-MM-DD'), 'Hipertensão controlada', 'Losartana 50mg');

INSERT INTO Consulta (id_paciente, id_medico, data_consulta, diagnostico, receita)
VALUES (2, 2, TO_DATE('2025-11-11', 'YYYY-MM-DD'), 'Infecção viral leve', 'Repouso e hidratação');

-- Internações
INSERT INTO Internacao (id_paciente, id_setor, data_entrada, observacoes)
VALUES (1, 2, TO_DATE('2025-11-09', 'YYYY-MM-DD'), 'Monitoramento cardíaco contínuo');

-- =============================
-- 3. CONSULTAS ÚTEIS
-- =============================

-- Listar todas as consultas realizadas
SELECT c.id_consulta, p.nome AS paciente, m.nome AS medico, e.nome_especialidade, c.data_consulta, c.diagnostico
FROM Consulta c
JOIN Paciente p ON c.id_paciente = p.id_paciente
JOIN Medico m ON c.id_medico = m.id_medico
JOIN Especialidade e ON m.id_especialidade = e.id_especialidade;

-- Mostrar pacientes internados atualmente
SELECT i.id_internacao, p.nome AS paciente, s.nome_setor, i.data_entrada
FROM Internacao i
JOIN Paciente p ON i.id_paciente = p.id_paciente
JOIN Setor s ON i.id_setor = s.id_setor
WHERE i.data_saida IS NULL;

-- Quantidade de consultas por especialidade
SELECT e.nome_especialidade, COUNT(c.id_consulta) AS total_consultas
FROM Consulta c
JOIN Medico m ON c.id_medico = m.id_medico
JOIN Especialidade e ON m.id_especialidade = e.id_especialidade
GROUP BY e.nome_especialidade;
